### ISSUE TITLE
Display the state - open or closed - in the card

### ISSUE THREAD

**Issue by hajo62** [panbachi/tankerkoenig-card#2]
Maybe one could do a color coding of the opening state? If a station is closed, the total line or the values could be shown in a i.e. gray background...

![image](https://user-images.githubusercontent.com/15800980/74612508-42c3c000-5106-11ea-92fe-764a714f0ff3.png)

**Comment by jressel01** [comment]
> 
> 
> Maybe one could do a color coding of the opening state? If a station is closed, the total line or the values could be shown in a i.e. gray background...
> 


![mit status](https://user-images.githubusercontent.com/70316907/99715985-cd778800-2aa7-11eb-8de4-647b3ec7e6ad.PNG)

i have added a circle with open and closed. you only have to edit the tankerkoenig-card.js and the card
