### ISSUE TITLE
No value visible

### ISSUE THREAD

**Issue by eloo** [panbachi/tankerkoenig-card#6]
Hi,

it seems that with the latest HA version your card is broken. 

![image](https://user-images.githubusercontent.com/2631895/136661232-c6978cb8-75ff-46ea-b5d0-54e68f220b70.png)

It seems that the value is added as attribute but the slot is not populated with any value

![image](https://user-images.githubusercontent.com/2631895/136661277-7bbcece6-c285-48b6-a9ff-2f7655a92097.png)

HA-Version: Home Assistant 2021.10.2

Thanks

**Comment by bussio** [comment]
Got the same problem here too.

**Comment by Kurisutian** [comment]
Same here

**Comment by larsf96** [comment]
This is most likely related to the following commit:
https://github.com/home-assistant/frontend/commit/d5ca7e1719ddc9d4e6c0965d6df0941b5321d9dd#diff-b8002834ef61d61ad34b9a60de20b1645e1561451b8abaf2501ffcb2e13a71dc

The value property has been removed there. The value must be injected in another way I guess

**Comment by eloo** [comment]
Thanks for the fix.
I can confirm that its now working as expected.
